version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
